CREATE TABLE layouts (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    fields JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE comparison_runs (
    id UUID PRIMARY KEY,
    run_index BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    run_name TEXT NOT NULL,
    old_layout_id UUID NOT NULL REFERENCES layouts(id),
    new_layout_id UUID NOT NULL REFERENCES layouts(id),
    old_date_of_download TIMESTAMPTZ NOT NULL,
    old_origin_file_name TEXT NOT NULL,
    new_date_of_download TIMESTAMPTZ NOT NULL,
    new_origin_file_name TEXT NOT NULL,
    processing_started_at TIMESTAMPTZ NOT NULL,
    processing_duration_ms BIGINT,
    old_row_count BIGINT,
    new_row_count BIGINT,
    CHECK (processing_duration_ms IS NULL OR processing_duration_ms >= 0),
    CHECK (old_row_count IS NULL OR old_row_count >= 0),
    CHECK (new_row_count IS NULL OR new_row_count >= 0)
);

CREATE TABLE delta_rows (
    id BIGSERIAL PRIMARY KEY,
    comparison_id UUID NOT NULL REFERENCES comparison_runs(id) ON DELETE CASCADE,
    composite_primary_key TEXT NOT NULL,
    change_type TEXT NOT NULL CHECK (change_type IN ('modified', 'added', 'removed')),
    old_data JSONB,
    new_data JSONB,
    changed_fields JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX delta_rows_comparison_type_idx ON delta_rows (comparison_id, change_type);

CREATE TABLE scheduled (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    frequency TEXT NOT NULL CHECK (frequency IN ('one_time', 'daily', 'weekly', 'monthly')),
    run_at TIMESTAMPTZ NOT NULL,
    old_path TEXT NOT NULL,
    new_path TEXT NOT NULL,
    old_layout_id UUID NOT NULL REFERENCES layouts(id),
    new_layout_id UUID NOT NULL REFERENCES layouts(id),
    archive_path TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_run_at TIMESTAMPTZ,
    error_message TEXT
);

CREATE INDEX scheduled_due_idx ON scheduled (run_at) WHERE status = 'pending';

CREATE TABLE scheduled_runs (
    id BIGSERIAL PRIMARY KEY,
    scheduled_id BIGINT NOT NULL REFERENCES scheduled(id) ON DELETE CASCADE,
    comparison_id UUID NOT NULL REFERENCES comparison_runs(id) ON DELETE CASCADE,
    old_filename TEXT NOT NULL,
    new_filename TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scheduled_id, old_filename, new_filename)
);
