CREATE TABLE layouts (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    fields JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE comparison_runs (
    id UUID PRIMARY KEY,
    run_index BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    run_name TEXT NOT NULL,
    old_layout_id UUID NOT NULL REFERENCES layouts(id),
    new_layout_id UUID NOT NULL REFERENCES layouts(id),
    old_date_of_download TIMESTAMPTZ NOT NULL,
    old_origin_file_name TEXT NOT NULL,
    new_date_of_download TIMESTAMPTZ NOT NULL,
    new_origin_file_name TEXT NOT NULL,
    processing_started_at TIMESTAMPTZ NOT NULL,
    processing_duration_ms BIGINT,
    CHECK (processing_duration_ms IS NULL OR processing_duration_ms >= 0)
);

CREATE TABLE delta_rows (
    id BIGSERIAL PRIMARY KEY,
    comparison_id UUID NOT NULL REFERENCES comparison_runs(id) ON DELETE CASCADE,
    composite_primary_key TEXT NOT NULL,
    change_type TEXT NOT NULL CHECK (change_type IN ('modified', 'added', 'removed')),
    old_data JSONB,
    new_data JSONB,
    changed_fields JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX delta_rows_comparison_type_idx ON delta_rows (comparison_id, change_type);
