-- Every comparison gets one durable numeric index. New source tables use this
-- same value in their table and index names, for example old_rows_42 and
-- new_rows_42.
ALTER TABLE comparison_runs
    ADD COLUMN run_index BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE comparison_runs
    ALTER COLUMN run_index SET NOT NULL,
    ADD CONSTRAINT comparison_runs_run_index_key UNIQUE (run_index);
